[package]
name = "pi"
version = "0.1.0"
authors = ["Nathan Leniz <nathan@pisolved.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
gcd = "2.0.1"
